### ISSUE TITLE
Tinker Shamir/ Tinkering Compressors should work on Raw Ore Forms

### ISSUE THREAD

**Issue by ToffeeMax** [Gamemode4Dev/GM4_Datapacks#1033]
Title, but
- Raw Gold > Raw Gold Blow
- Raw Iron > Raw Iron Block
- Raw Copper > Raw Copper Block
... ect

**Comment by catter1** [comment]
This is already implemented, no? [Raw Gold for example](https://github.com/Gamemode4Dev/GM4_Datapacks/blob/master/gm4_tinkering_compressors/data/gm4_tinkering_compressors/function/compress/raw_gold.mcfunction)

**Comment by BluePsychoRanger** [comment]
Yes, this is already implemented as of https://github.com/Gamemode4Dev/GM4_Datapacks/pull/656

However, the wiki is not updated, which may have caused the confusion.
https://wiki.gm4.co/Tinker_Shamir
