### ISSUE TITLE
Can't remove unwanted holographic tag

### ISSUE THREAD

**Issue by Lumguava** [Gamemode4Dev/GM4_Datapacks#1057]
**Describe the bug**
Minor issue but distracting. I played with the functions and ran the create_hologram and destroy_hologram. I died and created the hologram seen in the screenshot I provided. Don't know how to remove. Tried to place a nametag near it but to no avail.

**To Reproduce**
1. Run /function gm4_holographic_tags:create_hologram
2. After dying, run /function gm4_holographictags:destroy_hologram

**Expected behavior**
Produces unwanted tag seen in screenshot

**Screenshots**
![image](https://github.com/user-attachments/assets/58e9b2e8-3ea8-4ec1-913e-9c5fedac6fa9)

**Environment**
 - Minecraft version: 1.21.1
 - Server version: Fabric 0.16.5
 - Installed Datapacks: Vanilla Refresh, GM4 Holographic tags
 - Installed Mods:
[modlist.txt](https://github.com/user-attachments/files/17173371/modlist.txt)
 
Thanks for taking time to read!

**Comment by BluePsychoRanger** [comment]
Those functions are not meant to be run by players. You can use this command to kill the holographic tag (while standing near it):
```mcfunction
kill @e[type=area_effect_cloud,tag=gm4_hologram,limit=1,distance=..1]
```

**Comment by Lumguava** [comment]
Thank you! That did the trick
