### ISSUE TITLE
Build Pipeline Generates Broken `init.mcfunction` Files for Old Minecraft Versions

### ISSUE THREAD

**Issue by Bloo-dev** [Gamemode4Dev/GM4_Datapacks#1066]
**Describe the bug**
The `init.mcfunction` of modules downloaded for old versions (tested for 1.14) are not able to be installed as the `init.mcfunction` contains malformed mcfunction code.

**To Reproduce**
1. Download Liquid Tanks for 1.14
2. Create a new 1.14 world and put the module in the `datapacks` folder
3. Run `/reload`
4. Observe how Gamemode 4 announces 'updating', but the module does not install itself.

**Expected behavior**
The module should install itself.

**Fix**
The problem is caused by the pipeline adding double speechmarks in the module update/version lists `CustomName` tag in `init.mcfunction`, see screenshot below.

**Screenshots**
![Image](https://github.com/user-attachments/assets/438637e0-b134-4603-a2dc-9aced2fdd942)

**Environment**
 - Minecraft version: 1.14
 - Server version: 1.14 (SP)
 - Installed Datapacks: Ambrosia, Liquid Tanks
 - Installed Mods: None

**Additional context**
Additional older versions may be affected.

**Comment by misode** [comment]
I believe I've fixed this in #1076. It didn't bump the patch versions because those versions didn't have the release output comparing mechanism, but the new zips should at least work now.

![Image](https://github.com/user-attachments/assets/adcd13f0-4507-482f-aa28-b8d7dbe89bca)

**Comment by misode** [comment]
I've also pushed the same fix to the `ver/1.13` branch. Since `ver/1.15` we started using a different system which didn't require the nested string anymore, so 1.13 and 1.14 were probably the only affected versions.
