### ISSUE TITLE
Memory Clearing mechanism

### ISSUE THREAD

**Issue by SoBeeIt** [Gamemode4Dev/GM4_Datapacks#1072]
gamerule spawnChunkRadius (desired value)
execute as @_a_ at @_s_ run setworldspawn ~ ~ ~

**Comment by Bloo-dev** [comment]
Welcome to our repo, and thank you for creating an issue.

When posting issues, please use one of our issue templates and explain what your issue is about. Be it a feature request, or a bug report.
