### ISSUE TITLE
(Almost) all modules stopped working

### ISSUE THREAD

**Issue by Rockety521** [Gamemode4Dev/GM4_Datapacks#1079]
As the title implies, almost none of the modules are working. I have no idea how or why it happened, but as you can see on this screenshot, the advancements tab does not display the "Gamemode 4" tab, but the chat, wich is blurry, shows two blue messages: the "Checking for updates..." and "No updates found" that appear upon starting the game.

 ![Image](https://github.com/user-attachments/assets/cfe5b497-af0d-4f67-9279-246a0d5215a1)

For the "Almost" part, I tried creating a custom crafter, and it worked, even while the advancements tab didn't show up. 

![Image](https://github.com/user-attachments/assets/8e170a65-c4e2-4849-a667-5e45075df0f8)

However, while trying to create the boots of ostara within the UI of the custom crafters, nothing happened.

![Image](https://github.com/user-attachments/assets/8ca35612-f4a3-4aaa-831e-97ba77a5aaf0)

Something I find strange is that the crafting recipes (such as the boots of ostara's, ski poles and others) were appearing flawlessly on basic crafting tables, but after the disappearance of the Gamemode 4 advancements tab, the recipes never showed up anymore.

It's probably not a compatibility issue, since up until yesterday or so, desire lines (and all other datapacks) were working, even while other datapacks were installed.
And, if you need to know, no, I didn't install any new datapacks that might have caused the glitch to happen.

**Environment**
 - Minecraft version: 1.21.4
 - Installed Datapacks: Other than some (53) Gamemode 4 modules,  "Vanilla tweaks" and "Vanilla refresh"

**Comment by kruthers** [comment]
1.21.4 is not supported, there is an open pull request #1077, which contains update versions that are still being tested.

**Comment by Rockety521** [comment]
> 1.21.4 is not supported, there is an open pull request [#1077](https://github.com/Gamemode4Dev/GM4_Datapacks/pull/1077), which contains update versions that are still being tested.

Oh, my bad lol. May I close?

**Comment by Bloo-dev** [comment]
Did you just update from 1.21.3 to 1.21.4 or was this an install on a fresh 1.21.4 world?

**Comment by Bloo-dev** [comment]
Closing this issue than, as 1.21.4 is not supported yet. Sorry about the inconvenience and intransparancy. Sadly, nowadays you have to assume that all Minecraft updates completely break mods & data packs.

**Comment by misode** [comment]
@Rockety521 Just letting you know that all our data packs have been updated to 1.21.4
