### ISSUE TITLE
Cannot Create new Crafters

### ISSUE THREAD

**Issue by ToffeeMax** [Gamemode4Dev/GM4_Datapacks#140]
After trying to install Custom Crafting, creating Custom Crafting, installing master crafting and reloading, you cannot create a master crafter or any new custom crafters.

### Expected Behavior
You should be able to create any new Custom Crafters or Master Crafters

### Current Behavior
You cannot do the above

### Possible Solution
Credit to @misode - Believe it uses old clocking system

### Steps to Reproduce

- Install Custom Crafting
- Reload
- Create a crafter
- Install Master Crafting
- Reload
- Try and create new crafter

### Environment
Java 1.13.2
Clean World
Master Crafting Latest and Custom Crafting Latest

**Comment by misode** [comment]
I'm not sure how this went unnoticed, but for some reason the clocking system was never updated. Probably because it was in testing around the same time the new clocking system was rolled out.

Working on a fix.
