### ISSUE TITLE
Metallurgy Shamir (or something) that can be applied to any boots that grants the effect of not creating desire lines like Boots of Ostara

### ISSUE THREAD

**Issue by DataCrusade** [Gamemode4Dev/GM4_Datapacks#143]
It wouldn't give you the auto crop planting effect, just the inability to create desire lines for the wearer. This would solve the big complaint about desire lines in general that currently has no reasonable solution (the unreasonable solution being everyone wearing boots of ostara). Having a later-game ability to not have to worry about desire lines while still wearing good boots would solve that.

**Comment by Bluefire-610** [comment]
This was suggested before, however, shamirs are the last go-to option for implementing a mechanic. They won't replace any existing modules.
