### ISSUE TITLE
Cave Air not handled like air by most modules.

### ISSUE THREAD

**Issue by Bluefire-610** [Gamemode4Dev/GM4_Datapacks#149]
Most modules don't treat Cave Air the same as air. As a result modules with air checks don't work as intended in caverns, natural ponds, ravines, dungeons…
### Expected Behavior
The Module should treat Cave Air just like normal air.

### Current Behavior
Cave Air is treated like any non air block.

### Possible Solution
Create a block tag #air, maybe even include it in the base.

### Affected Modules (extend this list in the comments)
Shroomites (spores see cave air as a solid block)
Phantom Scarecrows (rockets explode in cave air)

**Comment by misode** [comment]
Including common tags (like `#air`) in the base seems like a bad idea because that's going to cause incompatibility issues.

**Comment by Kroppeb** [comment]
I think we should include a `#air` as many modules have problems and Mojang still hasn't added a tag themselves.

**Comment by Kroppeb** [comment]
List of modules testing for `air`:

*  Boots of Ostara: 
    * Crops won't be planted on newly placed farmland in caves: `gm4_boots_of_ostara\data\boots_of_ostara\functions\active.mcfunction`
* Custom Crafters: Not affected as the check is for when a crafter is broken, will always be `air`
* Phantom Scarecrows:
    * rockets explode in cave air: `gm4_phantom_scarecrows\data\phantom_scarecrows\tags\blocks\traversable.json`
* Pig tractors: same as above but it's littered with `air` checks, I think some of them might be able to be deleted
* Shroomites: 
    * spores see cave air as a solid block: `gm4_shroomites\data\shroomites\tags\blocks\shroom_rootable.json`
* Zauber Cauldrons:
    * Idk what's happening with the poison potion here so idk if it's affected: `gm4_zauber_cauldrons\data\zauber_cauldrons\functions\recipes\potions\poison.mcfunction`

**Comment by Bluefire-610** [comment]
Yes, Zauber Cauldrons is affected. Putting up the cauldron in a cave will prevent cobwebs from spawning upon recipe execution (poison IV potion). Though this will only work once since breaking the cobwebs would place air again

**Comment by AndanteDevs** [comment]
This doesn't really affect much, but `minecraft:void_air` as well

**Comment by misode** [comment]
Reopen as this was only patched in 1.13
