### ISSUE TITLE
TPS drops when running shroomites.

### ISSUE THREAD

**Issue by Bluefire-610** [Gamemode4Dev/GM4_Datapacks#18]
When covering a large area with shroomites the server experiences tps drops if - and only if- the area isn't fully loaded / near the edge of loaded chunks. As of right now the reason for this is unknown.

**Comment by ToffeeMax** [comment]
Possible Suggestion: Lazy Chunk Loading of Entites, since you are executing off them and they are processed differently

**Comment by misode** [comment]
I'm unable to reproduce this. I have about 180 entities loaded (50 shrooms and 180 spores) in a peaceful flatworld with doMobSpawning on false. I get an almost constant 4 mspt. See this clip: https://gfycat.com/UnawareBitterHare

**Comment by Bluefire-610** [comment]
I'll close this for now. Keeping shroomites in mind as a possible lag-source, though.
