### ISSUE TITLE
Multiple Advancements and untitled

### ISSUE THREAD

**Issue by Hero29** [Gamemode4Dev/GM4_Datapacks#21]
http://prntscr.com/l0kjk1 
ZipRails has 2 Whee... advancements and there are 3 unnamed/labeled advancements

**Comment by misode** [comment]
What datapacks do you have enabled?

**Comment by Hero29** [comment]
@misode everything but weighted armor

**Comment by misode** [comment]
@Bluefire-610 @sparks0 
Better fire still has the default advancement, Shroomites has the Ziprails advancement and Standard crafting still has the default advancement

**Comment by Bluefire-610** [comment]
Better Fire's, Shroomites' and Ziprails' advancements were fixed.
