### ISSUE TITLE
Shroomites not spreading

### ISSUE THREAD

**Issue by misode** [Gamemode4Dev/GM4_Datapacks#23]
The shroomite spore is not spreading after summoned one using the following command
```
/execute align xyz run summon area_effect ~0.5 ~0.5 ~0.5 {Duration:2000000000,Tags:[gm4_shroomite_spore]}
```
I believe this is caused by an incorrect tag reference in `shroomites:main`. On line 9, the tag `gm4_shroomite` is used instead of `gm4_shroomite_spore` everywhere else. The tag `gm4_shroomite` isn't used anywhere else. After changing the tag the spores started spreading correctly.

**Comment by Bluefire-610** [comment]
I'm checking the version I have on a test server, one sec

**Comment by Bluefire-610** [comment]
You're summoning a spore, not a shroom. To summon a shroom place this command block above a `red_mushroom`:
`summon minecraft:area_effect_cloud ~ ~-1.45 ~ {Tags:["gm4_shroomite","gm4_shroomite_shroom"],Duration:2147483647,Particle:"mycelium",Radius:0.3}`

Shroomites is not recommended for casual survival yet.

**Comment by misode** [comment]
That explains a lot. May I ask why a `gm4_shroomite` tag is applied and used here instead of using the `gm4_shroomite_shroom` tag?

**Comment by Bluefire-610** [comment]
Shroomite Shrooms are also randomly spawned by mooshrooms, however, this process is *really* slow.

**Comment by Bluefire-610** [comment]
`gm4_shroomite` was meant as a collective tag for both spores and shrooms, it is used when a command needs to run on both shrooms and spores.
