### ISSUE TITLE
Metallurgy Levity can overwrite or clear an existing levitation effect

### ISSUE THREAD

**Issue by misode** [Gamemode4Dev/GM4_Datapacks#233]
This allows players with the levity shamir equipped to completely avoid getting a levitation effect. 

A solution would be to check if the player already has a levitation effect before trying to apply it, and only clear a level 255 levitation effect.

**Comment by jpeterik12** [comment]
This is a problem now as this now affects End Fishings's Ender Puffer.

**Comment by Bloo-dev** [comment]
Metallurgy will be discontinued in 1.17. This bug will stay relevant for legacy versions, but won't be fixed.
