### ISSUE TITLE
[LT:Potion Liquids] Witches only fill tanks up to 10 buckets instead of the new 100 limit

### ISSUE THREAD

**Issue by Kroppeb** [Gamemode4Dev/GM4_Datapacks#238]

**Comment by Bluefire-610** [comment]
This is not a bug, witches have never filled up a tank completely. This is to make potion farms just a bit harder to build.

**Comment by Kroppeb** [comment]
Yes, I remembered that this used to be like this, but I noticed that shulkers don’t have this restriction so I thought that it was decided to remove said restriction. I assumed the max of 30 bottles was there because the max liquid limit used to be 30 buckets, and my midnight brain forgot that this means 90 bottles.
