### ISSUE TITLE
Cannot expand on Orbis Structures

### ISSUE THREAD

**Issue by BluePsychoRanger** [Gamemode4Dev/GM4_Datapacks#261]
The current version of Orbis allows for expansion of chunk generation, but not structure generation. It allows only two type of structures: dungeons and towers. But what if someone wants to generate a new type of structure?

### Expected Behavior
The function called to check for structures should be called by a function tag, similar to how chunk generation is called

### Current Behavior
The function called to check for structures is implemented directly into the orbis base, allowing for checking for dungeon generation or tower generation

### Possible Solution
The following code should be changed in `orbis:chunk/generate.mcfunction`
`# try to spawn a structure before any chunk modifications have been done
function orbis:structure/chunk`
->
`# try to spawn a structure before any chunk modifications have been done
function #orbis:structure/chunk` 

and add a function tag `structure/chunk.json` to call the function `orbis:structure/chunk`

**Comment by misode** [comment]
The current implementation allows for two easy to use hooks for structure spawning. One on the surface and one underground. This is not only limited to dungeons and towers.

If an expansion wants to do something else, it can use the generic `#orbis:chunk/generate` tag

**Comment by BluePsychoRanger** [comment]
ah okay
