### ISSUE TITLE
Using mob conversion to get a potion villager does not work

### ISSUE THREAD

**Issue by kyrkis** [Gamemode4Dev/GM4_Datapacks#268]
When converting a witch to a villager using mob conversion it becomes a villager with no job, if you click it its inventory quickly flashes up and goes down again because it has no work station. Giving it one results in it becoming a villager of its workstations type: brewing stand into a normal cleric.

### Expected Behavior
Its supposed to become a cleric type who sells potions, idk if its supposed to need a workstation or not but at least you should be able to open its inventory

### Current Behavior
There is no way to get acess to its trades

### Steps to Reproduce
1. Have a witch on gm4 PSV
2. Make it into a villager using mob conversion
3. Be unable to open its inventory.

### Environment
Well I did do it in the nether although i do not think that should matter.
It was in multiplayer, Gm4 PSV
Well, i got all the other modules on gm4, i cant list them
Using 1.14.4

**Comment by Kroppeb** [comment]
Should have been fixed by #262

**Comment by misode** [comment]
The mob conversion module on the public server is 2 versions behind.

**Comment by kyrkis** [comment]
Why's that? Misode?

**Comment by Bluefire-610** [comment]
Because no-one has updated the module on the server yet
