### ISSUE TITLE
Mysterious Midnights item doesn't get consumed correctly

### ISSUE THREAD

**Issue by misode** [Gamemode4Dev/GM4_Datapacks#269]
### Expected Behavior
When a bone, rotten flesh or slime ball spawns its corresponding mob, it removes the item.

### Current Behavior
The item isn't killed, causing mobs to be continuously spawned. This can cause massive lag problems.

### Steps to Reproduce
1. Wait for a mysterious midnight, or force one by setting the time
2. Drop a bone, rotten flesh or slime ball on the ground
3. Notice a mob spawns, but the item is still there

### Environment
This happens in 1.14.4 on the Public Server V

**Comment by Bluefire-610** [comment]
This is caused by spigot and might be fixable using some spigot setting.

**Comment by Kroppeb** [comment]
Yes, the gapple for witch conversion had the same issue so I added a fix for that in #263. The issue comes from spigot not allowing `Count` to be set to 0, while Minecraft does and kills the item which is a shortcut taken in some places.
