### ISSUE TITLE
Mending Tanks doesn't reset tanks properly

### ISSUE THREAD

**Issue by sparks0** [Gamemode4Dev/GM4_Datapacks#299]
If an experience tank is emptied while it is mending a tool, the tank can no longer accept experience to become a new experience tank.

### Expected Behavior
Standing on top of an empty tank with experience should turn it into an experience tank.

### Current Behavior
The tank does not react to the player and instead remains empty.

### Steps to Reproduce
1. Install Liquid Tanks and mending Tanks.
2.Create a new liquid tank.
3.Fill the tank with experience by standing on top of it.
4. Place a tool with low durability and the mending enchant in the first slot so the tool empties the liquid tank while it is being repaired.
5.Stand on top of the now empty tank with experience on you.
6. Notice the tank doesn't fill with XP.

### Environment
Tested on the GM4 stream and public servers.

**Comment by EpyonProjects** [comment]
Tested on GM4 Public Server, this is no longer the case.
