### ISSUE TITLE
Boots of Ostara not working

### ISSUE THREAD

**Issue by Hero29** [Gamemode4Dev/GM4_Datapacks#30]
I have crafted the boots of Ostara but the desire lines effects are still happening, and carrots in the 9th slot of my inventory are not being planted

**Comment by misode** [comment]
You need items in the offhand, (changed in this version). As for the desire lines effect still happening, I'll look into it.

**Comment by misode** [comment]
Okay I see I swapped the words `extension` and `expansion`. Fix incoming!
