### ISSUE TITLE
1.14 standard crafting easy dulplication

### ISSUE THREAD

**Issue by p0larBeaRrage** [Gamemode4Dev/GM4_Datapacks#309]
### Current Behavior
with the new block in 1.14 [the stone cutter] you can make stair from any stone resource in a 1:1 ratio, however, with the standard crafting module you can convert stair in a 2:3 ratio. in other words
4 cobble = 4 stairs
4 stairs = 6 cobble

this applies for all stone materials that can be used in the stonecutter (bricks can be used as well)

### Possible Solution
have the stone material stairs give back in a 1:1 ratio is the only viable solution I can see

### Steps to Reproduce
1.
![image](https://user-images.githubusercontent.com/56623804/66892764-4223fb80-f038-11e9-8205-4cc4460734ed.png)

2.
![image](https://user-images.githubusercontent.com/56623804/66892819-5f58ca00-f038-11e9-903b-753fe0ea283e.png)

3.
![image](https://user-images.githubusercontent.com/56623804/66892845-6d0e4f80-f038-11e9-8fef-112d9512867e.png)

### Environment
I found this scrolling through the standard crafting recipes in the standard crafting module and seeing the stairs back to blocks recipe, I used the stone cutter to make stairs because it's more efficient, then realized I could duplicate using that recipe.
just remember this is only a 1.14+ issue

**Comment by Bluefire-610** [comment]
Thank you for reporting this issue, it should be fixed now (thanks to @misode )
