### ISSUE TITLE
Simplified multiplier

### ISSUE THREAD

**Issue by AndanteDevs** [Gamemode4Dev/GM4_Datapacks#33]
Am I right that the only purpose of {gm4_custom_crafters:{mutliplier:X}} is to have stackable crafting?
If so, instead of doing loads of extra processes, can't you just check for an item with the tag {gm4_custom_crafters:{multiply:true}} store the original stack size into a scoreboard, run the recipe checks, store the new stack size into a different scoreboard, multiply the two scoreboards together, store the multiplied score into the item's count and remove the multiply tag(edited)
This is what I did for my datapack, Vadditions:

```java
#@s = custom crafter unless block ~ ~ ~ #vadditions:holds/customcrafter{Items:[]}

#pre
execute store result score @s VADS_FrstStckSze run data get block ~ ~ ~ Items[0].Count

#sandstones to sand
execute if score @s VADS_SlotCount matches 1 if score @s VADS_StackSize matches ..16 if block ~ ~ ~ #vadditions:holds/customcrafter{Items:[{Slot:0b,id:"minecraft:sandstone"}]} run data merge block ~ ~ ~ {Items:[{Slot:8,id:"minecraft:sand",Count:4b,tag:{vadditions:{multiply:true}}}]}
(And further recipe checks...)
#post
execute store result score @s VADS_NewStckSze run data get block ~ ~ ~ Items[0].Count
scoreboard players operation @s VADS_NewStckSze *= @s VADS_FrstStckSze
execute if block ~ ~ ~ #vadditions:holds/customcrafter{Items:[{tag:{vadditions:{multiply:true}}}]} store result block ~ ~ ~ Items[0].Count byte 1 run scoreboard players get @s VADS_NewStckSze
execute if block ~ ~ ~ #vadditions:holds/customcrafter{Items:[{tag:{vadditions:{multiply:true}}}]} run data remove block ~ ~ ~ Items[0].tag.vadditions
```

**Comment by misode** [comment]
You actually don't even need the custom tag I think. It can just read the `Count` tag and use that as the multiplier. If you don't want multi crafting for your recipe you can just check if the `stack_size` is 1 in your extension module.

**Comment by AndanteDevs** [comment]
I used the custom tag due to the fact that it will run over and over again and eventually set the item count to be more than 127, deleting the item. If you only process items with a certain tag and then remove the tag from said items that doesn't happen.

**Comment by Bluefire-610** [comment]
This is exactly what we're doing with the `multiplier:int` tag, just that you're suggesting to use the `Count:int` tag instead. Using the custom integer tag is nicer for readability, though.

**Comment by misode** [comment]
> Using a custom integer tag is nicer for readability

Personally, I think `Count` makes much more sense. It's shorter, you don't have to remove the custom tag and people already know `Count` is used to set the count of the result.

**Comment by Bluefire-610** [comment]
I see where you're coming from as I ran into the same confusion when I was updating standard crafting, however, using costume tags became somewhat of a standard since we can rely on our own custom tags to be there. I'll leave this marked as `closed` and `won't fix` for now but I'll get into touch with special to see what he thinks.
