### ISSUE TITLE
Suggestion: Automatic animal breeding module

### ISSUE THREAD

**Issue by kyrkis** [Gamemode4Dev/GM4_Datapacks#35]
Add a module that works like this: you throw preferred food of an animal for example wheat at a cow and it goes into love mode. This would be veery useful for farms and such but idk if having to check all the time would cause lag.

**Comment by kyrkis** [comment]
well chickens are already that way kinda but they dont even need any food

**Comment by kyrkis** [comment]
but I do understand what you mean

**Comment by Bluefire-610** [comment]
Chickens already are that way, yes and they already cause issues. I guess it's up to the players which modules they install.

**Comment by AndanteDevs** [comment]
The thing I added with my own datapack was instead of breeding simply just give them regeneration as that can help. Still, breeding is the better idea!

**Comment by AndanteDevs** [comment]
Creating...

**Comment by AndanteDevs** [comment]
On the topic of lag for servers due to constant checking, the module uses GM4's clocking system instead of checking every tick, reducing the strain on the server.

**Comment by AndanteDevs** [comment]
Pull moved to #123
