### ISSUE TITLE
Conduction Shamir does not strike intuitively

### ISSUE THREAD

**Issue by BluePsychoRanger** [Gamemode4Dev/GM4_Datapacks#408]
**Describe the bug**
When the conduction shamir spawns the lightning bolt, the AEC is spawned at the player's feet, causing the AEC to always strike the player if the player's x-rotation is greater than 0.

**To Reproduce**
1. Hold the conduction sword
2. Deal enough damage for the indicator to turn yellow
3. Look downwards, just a little bit (the second rotation value in F3 should be positive)
4. Wait for the timer to run out
5. Player is struck by lightning

**Expected behavior**
The block the player is looking at is supposed to be struck with lightning.

**Fix**
in `successfully_depleted_charge.mcfunction` after the line that says 
`tp @e[type=area_effect_cloud,tag=gm4_conduction_raycast_point,distance=..2,limit=1] @s` 
add a line that says 
`execute as @e[type=area_effect_cloud,tag=gm4_conduction_raycast_point,distance=..0,limit=1] at @s run tp @s ~ ~1 ~`

**Comment by Bloo-dev** [comment]
This was fixed in PR #534.
