### ISSUE TITLE
Levity Affects Spectators

### ISSUE THREAD

**Issue by Bloo-dev** [Gamemode4Dev/GM4_Datapacks#416]
**Describe the bug**
Levity works on spectators. This means that spectators leave (visible!) cloud trails and get the slow falling effect.

**To Reproduce**
1. Put on some levity gear
2. Switch to spectator
3. Sneak

**Expected behavior**
Levity should ignore spectators.

**Fix**
Add a `gamemode=!spectator` selector.

**Environment**
 - Minecraft version: 1.15.2
 - Server version: 1.15.2 (Public Server 6)

**Comment by misode** [comment]
This also affects enderpuffs
