### ISSUE TITLE
Book Binders store lvl as Int

### ISSUE THREAD

**Issue by Bloo-dev** [Gamemode4Dev/GM4_Datapacks#430]
**Describe the bug**
When binding a book from pages in a book binder, the resulting enchanted book will have its enchantment lvl fields stored as `int`. Whilst this is supported by most parts of minecraft, modules that test specifically for `lvl:<something>s` will fail to detect this as they are expecting a short.
One module affected by this is Zauber, Crystals can't be crafted using these Book Binder books. As `lvl` should be a `short` by default, Book Binders should be adapted. However, the Book Binders module never actually specifies to store as an integer and the conversion is done by the game when copying the enchantments into storage.

**To Reproduce**
1. Craft an Enchanted Book from Pages
2. Inspect the NBT _before_ placing the Book in a container

**Expected behavior**
`lvl` should be a `short`

**Fix**
I really don't know.

**Workaround**
Placing the enchanted book in a container will update the `lvl` tags to be `shorts`.

**Environment**
 - Minecraft version: 1.15.2
 - Server version: 1.15.2, Paper (git-Paper-371), Public Server 6

**Additional context**

**Comment by AndanteDevs** [comment]
I haven't looked at the code, but if it only exists for a tick you can copy it to storage or something

**Comment by Bloo-dev** [comment]
This might be fixed in 1.17.1.

**Comment by Bloo-dev** [comment]
This no longer occurs in 1.17.
