### ISSUE TITLE
Future issues for 1.17

### ISSUE THREAD

**Issue by kruthers** [Gamemode4Dev/GM4_Datapacks#496]
**Describe the bug**
This is a general bug report to just track known issues for when updating to 1.17
This is a dev bug report and will be replaced with correct ones for each module when we update

Lantern Load has had a major update and wbase will need updating to conform with it https://github.com/LanternMC/load 

**Fix**
We wait until 1.17 update time

**Other issues**
Pack format has changed to 7 for 1.17

**Broken Modules**
- Smelteries - *Uses replace item*
- Liquid Tanks - *Replace item*
- Crossbow Cartridges - *Uses replace item*
- Lumos Shamir - *Used "minecraft:grass_path" in block tag gm4_lumos_shamir:torch_unplacable, its now "mincraft:dirt_path"*
- Tunnel Bores - *Used "minecraft:grass_path" in block tag gm5_tunnel_bores:not_rail_solid, its now "mincraft:dirt_path"*

**Broken functionality**
- Bat Grenades - *Bat loot table is broken*

**New feature that need adding for 1.17**
- Metallurgy - Sensus Shamir is missing copper

*Please comment any other issues found and they will be added to this list*

**Comment by Luewd** [comment]
All modules will need to update to account for `"pack_format": 7`. Additionally a change has been made to the "load" tags which is intended to be applied alongside the pack format update. See #535.

**Comment by kruthers** [comment]
No longer needed
