### ISSUE TITLE
Wormhole mixing with itself/nothing

### ISSUE THREAD

**Issue by kyrkis** [Gamemode4Dev/GM4_Datapacks#508]
When a one use wormhole is placed into a tank after an entity has already been placed under the tank (The mob is put under the empty tank and a wormhole is put in) the tank will teleport the mob correctly and empty out almost instantly. When this is repeated the mob does not teleport correctly (This is using the same location wormhole). The second mob is unclear where it goes but it does not end up at the specified location but instead teleports somewhere unknown.
What i believe is happening is that the first wormholes teleport data gets stored even though the tank is empty. But somehow the coodrinates got lost on the way. So when a new wormhole is placed into the tank it mixes with the first one (which lead to the same location which would result in no change). This teleports the mob to the average location between the destination and an unknown coordinate.

How to reproduce
1. Make a 9 use wormhole in the output location.
2. Put the wormhole in a tank and take out 9 1-use bottles.
3. At another location put a mob under an empty tank and place 1 of the 9 wormholes in it. This will teleport the mob to the right location.
4. Place another mob under the empty tank that previously teleported the last mob
5. The wormhole gets used up and the mob does not arrive at the right location.

Expected behaviour
I expected the second mob to be teleported to the right location as well as the wormholes lead to the exact same location.

Fix
I do not have many skills when it comes to coding/commands/datapacks but my idea of a fix would be to clear any data of wormholes from an empty tank. When the tank gets emptied any coordinates of previous wormholes should be deleted.

Environment
gamemode 4 psvi 
aprox date 19th of december 2020

Additional context
In this specific instance I teleported Villagers

**Comment by Bloo-dev** [comment]
Could not replicate. This might be an artifact of an entity teleportation memory effect we fixed in 18b0675e8f7b16332f9ddc1f00c3baed1bbcb2c6.
