### ISSUE TITLE
Empty tank mixes new wormhole with wormhole that was previously in the tank

### ISSUE THREAD

**Issue by kyrkis** [Gamemode4Dev/GM4_Datapacks#509]
**Describe the bug**
After mixing 100 buckets of wormholes and taking everything out (tank appeared empty on the outside as well and no more 1 use bottles could be extracted) And another batch of wormholes to mix was added the whole batch was off as if it had been mixed with the previous batch that was completely gone.

**To Reproduce**
1. Make a lot of wormholes
2. mix the wormholes
3. extract every wormhole
4. place new wormholes into the empty tank
5. the wormholes have now mixed with the old ones even though the tank was empty

**Expected behavior**
When the tank was empty i expected there was nothing the new wormholes would mix with

**Fix**
Clear any coordinates from tanks when theyre empty

**Environment**
Gm4 psvi server
aprox date 29th december 2020

**Additional context**
The first batch of mixed wormholes filled the tank to 100%

**Comment by Bloo-dev** [comment]
Could not replicate. This might be an artifact of an entity teleportation memory effect we fixed in 18b0675e8f7b16332f9ddc1f00c3baed1bbcb2c6.
