### ISSUE TITLE
Pig Tractors Crashes When Holding Hoe

### ISSUE THREAD

**Issue by edvb** [Gamemode4Dev/GM4_Datapacks#589]
**Describe the bug**
With the data pack installed whenever you hold a hoe in your hand it causes Minecraft to crash.

I can not reproduce this behavior before commit 61b8d800.

**To Reproduce**
1. Have pig tractors installed
2. Put hoe in your hot bar
3. Select hoe with your hand

**Environment**
 - Minecraft version: 1.16.5
 - Installed Datapacks: Other GM4 datapacks

**Comment by Bloo-dev** [comment]
I can not reproduce this bug, neither on my client (1.16.5, vanilla, just Pig Tractors) nor on a server (1.16.5, spigot, lots of GM4 Modules).
Are you sure your game isn't modded?

**Comment by Bloo-dev** [comment]
Also, the commit you linked does not change anything about Pig Tractors, are you sure you linked the right commit?

**Comment by Bloo-dev** [comment]
Can not reproduce.
