### ISSUE TITLE
Add more block types to Speed Paths

### ISSUE THREAD

**Issue by Compsogbrickus** [Gamemode4Dev/GM4_Datapacks#59]
A helpful and realistic addition to Speed Paths might be to add more block types that give speed to players, such as gravel, concrete dust, cobblestone, mossy cobblestone, sandstone, wooden planks, polished stones, stone bricks, bricks, and concrete. This could also apply to all slabs/stairs for each block, if applicable. Coarse dirt could work too, as it would be a good advantage to Desire Lines. This improvement would require duplication of the current main.mcfunction code.

**Comment by AndanteDevs** [comment]
Will this be added? If so, I could quickly do that.

**Comment by misode** [comment]
Personally I feel it'd take away the unique ability of path blocks to give you speed

**Comment by AndanteDevs** [comment]
I agree with that

**Comment by Compsogbrickus** [comment]
I  am suggesting this as a builder because most paths are not grass. It seems strange to have a main path block that does not really fit most build styles.

**Comment by Bluefire-610** [comment]
> Personally I feel it'd take away the unique ability of path blocks to give you speed

I agree with @misode here. Paths are something special.

**Comment by sparks0** [comment]
If I added it to any other block it would be coarse dirt because of desire lines but I don't think other blocks should have the same feature. Path blocks are specifically for paths but many of your suggestions might just be floors in houses.

**Comment by Compsogbrickus** [comment]
I suggested common materials that are used in real life for floors because they have good building qualities and are also used for outdoor walkways. Most of Ancient Citadel on PSIV was serviced by wood plank, stone, gravel, cobble, and stone brick paths, and I thought it was weird that those materials didn't have the same buff that path blocks did given the reasoning for speed on path blocks.

**Comment by Bluefire-610** [comment]
I'm closing this issue as it is unlikely to be implemented.
