### ISSUE TITLE
Ziprails Minecart Motion

### ISSUE THREAD

**Issue by AndanteDevs** [Gamemode4Dev/GM4_Datapacks#67]
### Expected Behavior
The minecart should reach the end of the tripwire string, 'fall out' of the string and, if there's a block in front of it, stop moving.

### Current Behavior
Currently, the minecart will keep trying to go forward, even if it hits a block, until you make sure the block above it is not a tripwire hook. 

### Possible Solution
Set ziprail minecarts to detect only tripwire **when changing motion**, instead of that AND tripwire hooks.

### Steps to Reproduce
1. Set up your ziprail
![2018-10-24_05 16 29](https://user-images.githubusercontent.com/36608902/47405938-20a57200-d74c-11e8-811f-368ff423dc48.png)
2. Place down the minecart, it will start moving forward (normal)
![2018-10-24_05 16 43](https://user-images.githubusercontent.com/36608902/47405937-20a57200-d74c-11e8-93a2-4e34fe78bc50.png)
3. Let it move to the end
![2018-10-24_05 16 56](https://user-images.githubusercontent.com/36608902/47405940-20a57200-d74c-11e8-9b4b-224ce877343f.png)
4. Break the block in front of it and it will move forwards ( it **should** stay still)
![2018-10-24_05 17 08](https://user-images.githubusercontent.com/36608902/47405939-20a57200-d74c-11e8-9d51-6d644efceedf.png)

### Environment
Singleplayer
All modules are installed
Void World (though biome is plains)
Minecraft 1.13.1 (OptiFine E4_pre2)

### Edit;
Whether or not the minecart should go forwards or not, in this instance the minecart latches back onto an **unpowered powered rail**: it should slow down the minecart regardless.

**Comment by AndanteDevs** [comment]
### Another possible solution
Check for a block at ^ ^ ^1 and set motion to nothing. Not sure how the carat coordinates work myself but I'd assume that'd work.

**Comment by AndanteDevs** [comment]
[Additionally](https://youtu.be/e8Vtjx7G7pM)

**Comment by SpiderRobotMan** [comment]
> [Additionally](https://youtu.be/e8Vtjx7G7pM)

Please provide some details to the videos here so we know what they are trying to show.

**Comment by Bluefire-610** [comment]
> [Additionally](https://youtu.be/e8Vtjx7G7pM), you can't modify the minecart's motion by getting inside of it and pressing the move keys.

This is due to the way ziprails work, on ziprails you can not change direction once you're hooked on. This won't be changed.

**Comment by sparks0** [comment]
This issue should now have been resolved by Misode's fix.
