### ISSUE TITLE
Trapped signs disconnect redstone wires

### ISSUE THREAD

**Issue by AndanteDevs** [Gamemode4Dev/GM4_Datapacks#74]
### Expected Behavior
The trapped sign should power the redstone wire and consequently affect the adjacent wires.

### Current Behavior
The redstone wire 'disconnects' from the adjacent wires.

### Possible Solution
The only way I can think of is to add a bunch of 'execute if's, which would take a lot of hard work.

### Steps to Reproduce
[Video](https://youtu.be/F0LeIaSjpg8)

### Environment
Singleplayer
All modules are installed
Minecraft 1.13.2 (OptiFine E4_pre3)

**Comment by SpiderRobotMan** [comment]
Does this cause those redstone wires to not connect to repeaters also?

**Comment by misode** [comment]
Impossible to fix

**Comment by Bluefire-610** [comment]
Due to the lacking compatibility of commands and "redstone powered state" it's not possible to fix this. Maybe a future minecraft version will allow us to fix this.
