### ISSUE TITLE
Module Clocks Stop Pulsing

### ISSUE THREAD

**Issue by Bloo-dev** [Gamemode4Dev/GM4_Datapacks#742]
**Describe the bug**
Sometimes schedule clocks of certain modules seem to stop pulsing. A reload fixes the issue.

**To Reproduce**
Sadly the behaviour is quite random and hard to reproduce.
Therefore, no step-by-step instructions can be provided. Try reproducing the environment outlined below instead.

**Expected behavior**
Schedule clocks should not stop pulsing.

**Fix**
Unknown.

**Environment**
 - Minecraft version: 1.18.1
 - Server version: Spigot 1.18.1 (\<add affected versions here\>)
 - Installed Datapacks: All Gamemode 4 Datapacks
 - Installed Mods: (redacted)

**Additional context**
Please note your own environment in the comments, in case this affects you too. Especially a list of datapacks will be of use for debugging this.

**Comment by misode** [comment]
This seems to be caused by https://github.com/PaperMC/Paper/issues/7293

**Comment by Bloo-dev** [comment]
> This seems to be caused by [PaperMC/Paper#7293](https://github.com/PaperMC/Paper/issues/7293)
This was fixed in papers 1.18.2 update.
