### ISSUE TITLE
Agile Pnuema can kick you from Server

### ISSUE THREAD

**Issue by ToffeeMax** [Gamemode4Dev/GM4_Datapacks#743]
**Describe the bug**
The agile pneuma can trigger and cause you to be kicked from a server for flying

**To Reproduce**
1. Have agile Pneuma
2. Take poison damage
3. Stand in space with clear sky
4. Float up
5. Wait for server to kick you

**Expected behavior**
_Unverified if this is fixable/expected_

**Environment**
 Gamemode 4 1.18 Paper Server

**Additional context**
This was reported by venemousbirds from the Discord and translated by myself.

**Comment by Bloo-dev** [comment]
This is default vanilla behaviour for high jump boost levels.
