### ISSUE TITLE
Ender Hoppers / Liquid Tanks Compatibility [Module]

### ISSUE THREAD

**Issue by Compsogbrickus** [Gamemode4Dev/GM4_Datapacks#76]
It's been previously noted that there's nothing preventing modules using the same base blocks from overlapping. Rather than simply allow/prevent that, I feel it would be better to make it so modules can combine into new forms.

When an Ender Hopper and a Liquid Tank are combined, a new tank/hopper with a special capacity is created. This block scans a 3x3x3 area above it for mobs, xp, and liquids. By default, it collects nothing, but when a liquid is added to the hopper, it begins attempting to collect that liquid from the environment, absorbing water, lava, liquids from mobs, and xp orbs, if relevant.

This would not affect the ability to add liquids manually to the tank, or the 9x3x9 item collection radius of the hopper.

**Comment by sparks0** [comment]
What do you mean by overlapping blocks?

**Comment by Compsogbrickus** [comment]
Hopper for the liquid tank = Hopper for the ender hopper

**Comment by Bloo-dev** [comment]
In 1.17 a tag called `gm4_machine` prevents this from happening.
