### ISSUE TITLE
Trapped Signs Possible Fix

### ISSUE THREAD

**Issue by Scommander** [Gamemode4Dev/GM4_Datapacks#77]
### Expected Behavior
When the Redstone around the sign is powered it should connect to other Redstone wire

### Current Behavior
When the Redstone is powered it disconnects to adjacent Redstone wire

### Possible Solution
If you set a redstone_wire with [power=2] it will visually connect to other Redstone wires - however, it gives off a one tick pulse meaning the Redstone doesn't visually turn on.

### Environment
Singleplayer
No other modules installed
1.13.2

**Comment by misode** [comment]
See #74 - There's no way to elegantly fix this. 

In the future, if you think you have a solution, you should comment on the original issue rather than creating a new issue.
