### ISSUE TITLE
Vibro is able to hurt Metallurgy Molds

### ISSUE THREAD

**Issue by venomousbirds** [Gamemode4Dev/GM4_Datapacks#820]
**Describe the bug**
If you do a charged up Vibro jump (sneaking down) multiple times on a Metallurgy mold, the mold gets destroyed and drops nothing.

**To Reproduce**
1. Create a Metallurgy mold
2. Charge up Vibro while standing on the block with the Metallurgy Mold
3. Jump up and sneak to create that Virbo shockwave on the block
4. Repeat step 2 and 3 until the mold disappears with no items dropped.

**Expected behavior**
Nothing should happen to the mold.

**Fix**
Vibro shouldn't get rid of the mold.

**Environment**
 - Minecraft version: 1.19.2 Client
 - Server version: Public Server (November 8th 2022)

**Comment by Bloo-dev** [comment]
This may already be fixed as metallurgy now uses armor stands instead of vexes. Verification required.
