### ISSUE TITLE
Add more blocks to BoO and allow for double handed armor stands for instant conversions

### ISSUE THREAD

**Issue by kyrkis** [Gamemode4Dev/GM4_Datapacks#848]
Currently BoO handles Moss and Grass Block conversions, this proposal is to add a few new conversions some of which are more similar to the current convertibles:

Vegetation type conversions:
Dirt/Coarse Dirt/Grass Block/ (maybe) Moss Block + Rooted Dirt -> Rooted dirt
Mud + Mangrove roots -> Muddy Mangrove Roots
Cobblestone + Moss Block -> Mossy Cobblestone
Stone Bricks + Moss Block -> Mossy Stone Bricks
(Infested Stone Bricks + Moss Block -> Infested Mossy Stone Bricks)

Fungal Type Conversions:
Dirt/Coarse Dirt + Mycelium -> Mycelium
Netherrack + Crimson Nylium -> Crimson Nylium
Netherrack + warped Nylium -> Warped Nylium

The Second part of this proposal is to improve on the priority system of double conversions like stone to moss to grass block. This would include allowing an armor stand or player wearing boots of Ostara and a moss block in one hand and a grass block in their other hand to instantly turn the stone into a grass block. The conversions would go main hand then off hand to allow for a choice in priority.

**Comment by jpeterik12** [comment]
I was talking with bloo previously, and the double conversion thing was something that I was supposed to get started on, but uni started. 
As for the additional conversion, I feel things like some of them feel a bit wrong, as currently BoO turns the ground into the block held, and combining (like for mossy cobblestone) feels different, but I can see the argument.

**Comment by Bloo-dev** [comment]
These are two separate issues:

### Dual Wielding
Yes, this should be made easier as the current behaviour is inconsistent.

### New Conversion Types
There's some good ones in here, but I do not agree with a bunch of them.

These ones make sense:
- Fungal Conversions

These are somewhat weird:
- Rooted Dirt
- Muddy Mangrove Roots
- Mossy Cobblestone
- Mossy Stone Bricks
- Infested Mossy Stone

The general rule-of-thumb is that the conversions should happen in-game either naturally or via bonemeal. Additionally, most of the vegetation type conversions have existing crafting recipes.
