### ISSUE TITLE
In-Game Text Appears Broken

### ISSUE THREAD

**Issue by Bloo-dev** [Gamemode4Dev/GM4_Datapacks#864]
**Describe the bug**
Most text components introduced by Gamemode 4 (item names, advancement names, item lore, etc.) do not show correctly, instead, a mix of numbers, letters and `%` is displayed.
**To Reproduce**
1. Install a Gamemode 4 Datapack.
2. Open the advancement tree or hover over a Gamemode 4 item.
3. The text will show as `%1s$s%3427655$s` or something similar

**Expected behavior**
Text components should be human-readable.

**Fix**
This issue is caused by a change Mojang made in 1.19.4 and affects all Datapacks that implement translate keys (i.e. ones that allow resource packs to add translations).
A proper fix will require replacing of all translate components within the affected Datapacks with the new format specified by Mojang, and perhaps a complicated update-functions to update old items, blocks, entites, etc.
PR #857 is currently WIP.

**A temporary fix, if applicable, is to stick with 1.19.3**

**Screenshots**
![image](https://user-images.githubusercontent.com/41843855/229368435-ac2e5106-7250-418a-b071-a6d5ed54d5d0.png)

**Environment**
 - Minecraft version: 1.19.4

**Comment by misode** [comment]
Fixed in #867
