### ISSUE TITLE
Reporting a vulnerability

### ISSUE THREAD

**Issue by igibek** [Gamemode4Dev/GM4_Datapacks#866]
Hello! 

I hope you are doing well! 

We are a security research team. Our tool automatically detected a vulnerability in this repository. We want to disclose it responsibly.  GitHub has a feature called **Private vulnerability reporting**, which enables security research to privately disclose a vulnerability. Unfortunately, it is not enabled for this repository. 

Can you enable it, so that we can report it? 

Thanks in advance! 

PS: you can read about how to enable private vulnerability reporting here: https://docs.github.com/en/code-security/security-advisories/repository-security-advisories/configuring-private-vulnerability-reporting-for-a-repository

**Comment by kruthers** [comment]
If you have a vulnerability please report it in our discord. Moist of our code in this pack is used in minecraft only, meeing the vulnerability is most likly in a connected libary we use. https://discord.gg/0qLGgv7JGfIXf45t
