### ISSUE TITLE
Fell out of world

### ISSUE THREAD

**Issue by morbility** [Gamemode4Dev/GM4_Datapacks#901]
**Describe the bug**
I was siting in a chair and broke the stairs and my player fell out of the world.

**To Reproduce**
1. Place stair with trapdoors on either side (for fake chair arms)
2. Place saddle
3. Sit
4. Break stairs while sitting on it
5. Black screen, fall out of world

**Expected behavior**
Stand up

**Fix**
Don't glitch players out of world when stairs they sit on are broken.

**Screenshots**
If applicable, add screenshots to help others understand your problem. (next comment)

**Environment**
 - Minecraft version: 1.20.1
 - Server version: 1.20.1
 - Installed Datapacks: GM4 (Server admin can provide more info if needed)
 - Installed Mods:

**Additional context**

**Comment by morbility** [comment]
![image](https://github.com/Gamemode4Dev/GM4_Datapacks/assets/13098396/81681048-05ae-4a88-bfe4-3b12a9a2438f)

This was the chair setup. 

Mods provided me with server side error code: "'WARN Unable to add mob to team "gm4_chairs" (that team probably doesn't exist)"

**Comment by morbility** [comment]
![image](https://github.com/Gamemode4Dev/GM4_Datapacks/assets/13098396/859362d9-c7fa-4a80-999d-4082cb85d2df)

**Comment by Bloo-dev** [comment]
![image](https://github.com/Gamemode4Dev/GM4_Datapacks/assets/41843855/7ac6dc65-03de-4c22-b0b7-52425200795b)

I've followed your instructions and isolated the issue. Here are my findings:

## Vanilla
The issue **does not occur** in **a vanilla environment**. Follow these steps to confirm this:
1. Create a new world using `Minecraft 1.20.1 vanilla`
2. Install Chairs
3. Place a Chair as displayed in the image above
4. Break the stair whilst you are sitting on it

➡️You will end up standing where the stair was. The Chair entity is killed shortly after the stair is broken, auto-dismounting you in that location.

## Falling into the Void
The issue **can be replicated** in **a vanilla environment**. Follow these steps to confirm this:
1. Create a new world using `Minecraft 1.20.1 vanilla`
2. Install Chairs
3. Place a Chair as displayed in the image above
4. Make the Chair entity (technically a `minecraft:pig`) leave the team `gm4_chairs`, e.g. using the following command: `/team leave @e[type=pig,tag=gm4_chairs,distance=..5,sort=nearest,limit=1]`
5. 4. Break the stair whilst you are sitting on it

➡️You will be teleported to `y=-10000` and die in the void.

## Conclusion
Using the additional information provided by you:
> Server admin provided me with server side error code: "'WARN Unable to add mob to team "gm4_chairs" (that team probably doesn't exist)"

It can be concluded that your **server environment is not a vanilla environment**. I'm guessing you're running a `paper` or `spigot` server that is not configured properly for running data packs. Below I've attached some recommended settings for `paper` or `spigot` servers to run data packs.

## Help for using Gamemode 4 and other Data Packs on paper/spigot 1.19+
By default paper/ spigot manipulates options that can cause commands and datapacks to behave differently, breaking some modules. To resolve these issues make sure all of the following options are set to the be same, ones in _italics_ are recommendations. Per world options only need to be set in the default world.
### `config/paper-global` (Paper)
`scoreboards.save-empty-scoreboard-teams` → true
### `config/paper-world-*` (Paper)
Having this set `paper-world-default` is fine
`entities.behavior.experience-merge-max-value` → 1000
`entities.behavior.phantoms-only-attack-insomniacs` → true (**only needed for end fishing** in the end)

`scoreboards.allow-non-player-entities-on-scoreboards` → true
### `spigot.yml` (Paper & Spigot)
`settings.log-named-deaths` → _false_
