### ISSUE TITLE
Soul Glass Issue

### ISSUE THREAD

**Issue by PaladinFallen** [Gamemode4Dev/GM4_Datapacks#917]
Describe the bug
No game-play issues cause server is down form maintenance, admins notice no issues as right now.

To Reproduce

Have datapack in folder
Run server
Read log

Expected behavior
No errors?

Fix
Code fix?

Screenshots
Output log
[Pastebin](https://pastebin.com/PMcBRvGh)

Environment

Minecraft version: Fabric 1.20.2
Server version: Paper 1.20.2

Installed datapacks:
#916 

Installed mods:
#916 

Other notes:

> On a side note, that is an impressively extensive list of datapacks and mods you are playing with. Mods and even some datapacks are sometimes known to cause problems for other datapacks, so I wish you the best of luck wrangling everything to play nicely together. We've had some experience getting datapacks to run in Paper (theres a guide in our discord) and might be able to lend a small hand if theres troubles, but for most of these mods you'll be on your own as we've never used them.

You're right, between two admins we are always trying to make things fun but not break anything. So far with just little editing we are able to run the server pretty well. And between the two of us, we try to remove every error we have show up. So I thank you for the help if we ever need it.

**Comment by misode** [comment]
Did we figure out why this happens? Is it a bug with paper or something we can fix?

**Comment by BluePsychoRanger** [comment]
Oh I actually just experienced this with the Guidebook. 1.20.2 requires strict JSON, so we need to reformat that predicate to use strings instead of booleans for "true"
