### ISSUE TITLE
Feature Request: Add Ability for Chairs to be used on slabs

### ISSUE THREAD

**Issue by ToffeeMax** [Gamemode4Dev/GM4_Datapacks#922]
As title says, but asked for a few places.
- Chairs current only uses stairs
- Allow pigs /saddle on slabs to add more variety

**Comment by Bloo-dev** [comment]
This has been discussed within the team briefly, and the consesus seemed slightly against it.

Personally, I think this wouldn't add too much and add issues such as not being able to tell the facing of a slab-chair. Hence, I am against this.
