### ISSUE TITLE
Custom crafters is only for 1.17 on the website

### ISSUE THREAD

**Issue by AndrecodeInBrackets** [Gamemode4Dev/GM4_Datapacks#938]
I watched some of your videos, i saw the crafters but i couldn't find it on the website cuz it is on 1.17 only.

The only way to install the datapack is by downloading (somehow cuz idk how) from github
[It is only on 1.17](https://gm4.co/modules/custom-crafters)

**Comment by kruthers** [comment]
Custom crafters is now included with the modules that require the custom crafter. It is no longer a separate module. So when you download them from the site customer crafters comes as part of the zip. You don't have to install it separately.

**Comment by Bloo-dev** [comment]
As explained above, this is not a bug. To add some more detail; If you download, e.g., [Forming Press](https://gm4.co/modules/forming-press) it will automatically include the Custom Crafters library for you, so as an end user you do no longer have to worry about downloading it, hence Custom Crafters isn't listed on the website, nor is it listed as a requirement on the website anymore.

If you are a developer and are looking to include this library in your own data pack you can get the library from our GitHub.
