### ISSUE TITLE
Ship GM4's datapacks as mods too (on Modrinth)

### ISSUE THREAD

**Issue by vico93** [Gamemode4Dev/GM4_Datapacks#954]
I think Modrinth can auto-ship datapacks as mods if the owner allows to. At least a couple of datapacks (and datapack+resource pack combos) on that have a mod version as well, that's why i suspect it's a trivial task to do.

If not, it's just a matter of take the datapack .zip file, add a couple of "descriptor" files alongside `pack.mcmeta` (`fabric.mod.json` for Fabric, `mods.toml` for Forge and i don't know if NeoForge uses another separate file or `mods.toml` as well), then switch the extension from `.zip` to `.jar` and upload separately as a mod. A quick guide about this can be found in [this page](https://news.lunareclipse.studio/article/sotc-instant-datapack-mod-ports) from the From the Fog creators.

The reason about this request is that shipping a "mod version" would ease the initial configuration (for modded players, of course) of a new world and would de-clutter the datapack list, and also would spare the need to use mods like [Data Loader](https://modrinth.com/mod/dataloader) to setup datapacks automatically for each new world created.

Example of how it looks when a datapack in MR also ships the "mod version":
![image](https://github.com/Gamemode4Dev/GM4_Datapacks/assets/3485505/b8c465a1-e2c1-44f2-a687-178b8f9d245f)

**Comment by Bloo-dev** [comment]
We discussed this in a recent meeting and came to the consensus that we will not package our data packs as mods for the following reasons:

### Incompatibility
Data packs bundled as mods suggest compatibility with other mods, as people are used to that from mod packs. However, they are still data packs, just with a nice coat on paint on top, and hence still have the same incompatibility issues.
There are plenty of mods (or even just mod loaders like forge) out there that mess with the way the base game functions and therefore break data packs.

### Support
Our data packs are designed for vanilla, and expect the game to behave like vanilla. We can not offer support nor fix issues with other mods altering the way the game works; and we don't want to offer something that we do not offer support for.

### Gamemode 4 is  Data Pack Project
We are a data pack project at the core. We're always glad to see people use our data packs in new, creative ways or environments, but we understand ourselves as data pack creators. The task of integrating these into a novel environment is left to others.
