### ISSUE TITLE
Moving custom recipes to official recipes

### ISSUE THREAD

**Issue by misode** [Gamemode4Dev/GM4_Datapacks#980]
The 1.20.5 update is adding custom item support for the output item of recipes. While this doesn't solve all our problems, we can get pretty far and we should explore our path forward. This issue lists some of the changes required if we decide to move to official recipes.

## Advantages
- Players can easily look up our items in the recipe book
- Our recipes will automatically work with the crafter,

## Module changes
Some modules would no longer make sense or would need to be rebranded. These are just my initial thoughts, nothing has been decided yet!
- **Auto Crafting**: Deprecate and remove in 1.21, since the crafter will cover everything. If too complicated to upgrade this module we could also remove it in 1.20.5
- **Standard Crafting**: Would now just be a recipe pack, maybe rebrand?
- **Forming Press**: Consider if we still need this module. Do we move all recipes to standard crafting?
- **Record Crafting**: Same as above
- **Lib Custom Crafters**: Remove

## Recipe changes
We cannot check for item components in the recipe input, and we currently use that for a few recipes. Some recipes can be modified, for others we would need to be a bit more creative.
- **Auto Crafter**: uses custom crafter in input, propose replacing with crafting table
- **Boots of Ostara**: preserves input item data
- **Ender Hopper Minecart**: uses an ender hopper in input: propose hopper minecart with ender eye and respawn anchor
- **Heart Canister Tier 2**: uses tier 1 in input
- **Liquid Minecart**: uses a liquid tank in input: propose using liquid tank recipe with hopper minecart instead of hopper
- **Crampons**: preserves input item data
- **Skis**: preserves input item data
- **Relocator**: uses silk touch books in input
- **Scuba Tank**: uses potion of water breathing in input
- **Soft Defuser**: uses potion of harming 2 and landmine in input
- **Secret Trapped Sign**: uses normal trapped sign, propose incorporating black dye in original recipe

**Comment by EpyonProjects** [comment]
Additional nbt crafting recipes:
- Heart Canisters T2 (requires T1)
- TNT Landmines' Soft Defuser (requires Landmine)

**Comment by BluePsychoRanger** [comment]
Liquid minecarts require a liquid tank to be crafted
