### ISSUE TITLE
Guidebook markers are not cleaned up correctly

### ISSUE THREAD

**Issue by misode** [Gamemode4Dev/GM4_Datapacks#985]
Guidebook is leaving around markers tagged `gm4_guide_<module>`. This may be an issue on Paper only.

**Comment by BluePsychoRanger** [comment]
Fixed in #1015 with the removal of runtime alphabetical sort. All markers that were left over will not be automatically deleted though. This command can safely delete all extraneous markers:
`/execute as @e[type=marker] if data entity @s data.toc_line run kill @s`
`/kill @e[type=marker,tag=gm4_guide_sorter]`

**Comment by Bloo-dev** [comment]
> Fixed in #1015 with the removal of runtime alphabetical sort. All markers that were left over will not be automatically deleted though. This command can safely delete all extraneous markers: `/execute as @e[type=marker] if data entity @s data.toc_line run kill @s` `/kill @e[type=marker,tag=gm4_guide_sorter]`



> Fixed in #1015 with the removal of runtime alphabetical sort. All markers that were left over will not be automatically deleted though. This command can safely delete all extraneous markers: `/execute as @e[type=marker] if data entity @s data.toc_line run kill @s` `/kill @e[type=marker,tag=gm4_guide_sorter]`



> Fixed in #1015 with the removal of runtime alphabetical sort. All markers that were left over will not be automatically deleted though. This command can safely delete all extraneous markers: `/execute as @e[type=marker] if data entity @s data.toc_line run kill @s` `/kill @e[type=marker,tag=gm4_guide_sorter]`

Closing this, even if it may still be an issue in 1.20.
