### ISSUE TITLE
Ziprails : expected behaviour no ?

### ISSUE THREAD

**Issue by uczpre** [Gamemode4Dev/GM4_Datapacks#995]
Vannila Minecraft btw
while the expected use case may require an extra rail under the tripwire , i cant see why it shouldnt work without one. i mean , it did work in the end (sort of)

https://github.com/Gamemode4Dev/GM4_Datapacks/assets/152762421/4e8991a1-d950-492b-bb25-5efbfcd4de49

**Comment by Bloo-dev** [comment]
The video you attached does not render.

Anyways, a rail under the tripwire is **required** by design, it is not optional! The minecart only hooks into the string, not the hook.
